### ISSUE TITLE
Need Instructions on how to use it

### ISSUE THREAD

**Issue by hemanth-avs** [SinglePageBookProject/IT_notes#1]
@earizon Find the repo interesting.  Had difficulty using it.

View in github.io is different when running locally

![image](https://user-images.githubusercontent.com/5846263/52919196-666ee300-32c5-11e9-91d5-656e793d7ec3.png)

Local server page

![image](https://user-images.githubusercontent.com/5846263/52919203-830b1b00-32c5-11e9-9728-d0551f287f1a.png)

Which view I need to use?

**Comment by earizon** [comment]
The correct one is that on github.io.

Right now you will need to manually create the /IT_notes directory and hardlink to map_v1.css / map_v1.js to make it work locally. 

There is a mismatch in the github.io/local URLs paths since github forces to add the /IT_notes prefix.
